#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001-workout-history (Workout History)

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 001-workout-history"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/royabitbol/Development/private/fitracker"

# Check if we're in the right directory
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
    echo -e "${RED}Error: package.json not found. Make sure you're in the project root.${NC}"
    exit 1
fi

cd "$PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start after ${max}s${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."

if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START FRONTEND DEV SERVER
# ============================================

echo ""
echo "Starting Vite dev server..."

# Kill any existing process on port 5173
lsof -ti:5173 | xargs kill -9 2>/dev/null || true

# Start Vite in background
npm run dev &
VITE_PID=$!

# Wait for Vite to be ready
wait_for_service 5173 "Vite Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://localhost:5173"
echo ""
echo "Dev Server PID: $VITE_PID"
echo ""
echo "To stop the server:"
echo "  kill $VITE_PID"
echo ""
echo "========================================"
echo "Ready to implement Workout History feature"
echo "========================================"
